export const formulas = [
  {
    id: 1,
    formula: "\\sqrt{x}",
    latex: "\\sqrt{}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 2,
    formula: "\\frac{x}{y}",
    latex: "\\frac{}{}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 3,
    formula: "\\sum_y^x",
    latex: "\\sum_{}^{}",
    type: "basic",
    fontSize: 10,
    name: "sum",
  },
  {
    id: 4,
    formula: "x^y",
    latex: "\\^{}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 5,
    formula: "x^2",
    latex: "\\^{2}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 6,
    formula: "x_y",
    latex: "\\_{}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 7,
    formula: "\\log_x y",
    latex: "\\log_{} {}",
    type: "basic",
    fontSize: 10,
  },
  {
    id: 8,
    formula: "\\prod_x^y",
    latex: "\\prod_{}^{}",
    type: "basic",
    fontSize: 10,
    name: "prod",
  },

  {
    id: 9,
    formula: "\\int",
    latex: "\\int",
    type: "basic",
    fontSize: 15,
    name: "int",
  },
  {
    id: 10,
    formula: "\\int_{x}^{y}",
    latex: "\\int",
    type: "basic",
    fontSize: 15,
    name: "int",
  },
  {
    id: 11,
    formula: "\\oint",
    latex: "\\oint",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 12,
    formula: "\\lim_{x\\to y}",
    latex: "\\lim_{{x} \\to {}}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 13,
    formula: "\\lim_{x\\to \\infty}",
    latex: "\\lim_{{x} \\to \\infty}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 35,
    formula: "\\sin",
    latex: "\\sin",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 36,
    formula: "\\cos",
    latex: "\\cos",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 37,
    formula: "\\tan",
    latex: "\\tan",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 38,
    formula: "\\cot",
    latex: "\\cot",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 39,
    formula: "\\sin^{-1}",
    latex: "\\sin^{-1}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 40,
    formula: "\\cos^{-1}",
    latex: "\\cos^{-1}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 41,
    formula: "\\log_{10} y",
    latex: "\\log_{10} {}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 42,
    formula: "\\log_2 y",
    latex: "\\log_2 {}",
    type: "basic",
    fontSize: 15,
  },

  {
    id: 43,
    formula: "\\ln_y x",
    latex: "\\ln_{} {}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 44,
    formula: "\\ln x",
    latex: "\\ln {}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 45,
    formula: "\\ln_{10} x",
    latex: "\\ln_{10} {}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 14,
    formula: "\\pi",
    latex: "\\pi",
    type: "basic",
    fontSize: 20,
  },
  {
    id: 15,
    formula: "\\infty",
    latex: "\\infty",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 16,
    formula: "\\to",
    latex: "\\to",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 17,
    formula: "\\alpha",
    latex: "\\alpha",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 18,
    formula: "\\beta",
    latex: "\\beta",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 19,
    formula: "\\gamma",
    latex: "\\gamma",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 20,
    formula: "\\delta",
    latex: "\\delta",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 21,
    formula: "\\epsilon",
    latex: "\\epsilon",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 22,
    formula: "\\zeta",
    latex: "\\zeta",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 23,
    formula: "\\eta",
    latex: "\\eta",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 24,
    formula: "\\theta",
    latex: "\\theta",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 25,
    formula: "\\iota",
    latex: "\\iota",
    type: "greek",
    fontSize: 15,
  },

  // latex vectors

  {
    id: 27,
    formula: "\\overleftarrow{xy}",
    latex: "\\overleftarrow{xy}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 28,
    formula: "\\overline{xy}",
    latex: "\\overline{xy}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 29,
    formula: "\\overrightarrow{xy}",
    latex: "\\overrightarrow{xy}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 30,
    formula: "\\lambda",
    latex: "\\lambda",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 31,
    formula: "\\mu",
    latex: "\\mu",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 32,
    formula: "\\phi",
    latex: "\\phi",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 33,
    formula: "\\lceil x \\rceil",
    latex: "\\lceil {} \\rceil",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 34,
    formula: "\\lfloor x \\rfloor",
    latex: "\\lfloor {} \\rfloor",
    type: "basic",
    fontSize: 15,
  },
  //operators
  {
    id: 46,
    formula: "\\times",
    latex: "\\times",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 47,
    formula: "\\div",
    latex: "\\div",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 48,
    formula: "\\pm",
    latex: "\\pm",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 49,
    formula: "\\mp",
    latex: "\\mp",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 50,
    formula: "\\cdot",
    latex: "\\cdot",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 51,
    formula: "\\cup",
    latex: "\\cup",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 52,
    formula: "\\cap",
    latex: "\\cap",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 53,
    formula: "\\neq",
    latex: "\\neq",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 54,
    formula: "\\leq",
    latex: "\\leq",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 55,
    formula: "\\geq",
    latex: "\\geq",
    type: "basic",
    fontSize: 15,
  },
  // rest of greek letters
  {
    id: 56,
    formula: "\\nu",
    latex: "\\nu",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 57,
    formula: "\\xi",
    latex: "\\xi",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 58,
    formula: "\\omicron",
    latex: "\\omicron",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 59,
    formula: "\\pi",

    latex: "\\pi",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 60,
    formula: "\\rho",
    latex: "\\rho",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 61,
    formula: "\\sigma",
    latex: "\\sigma",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 62,
    formula: "\\tau",
    latex: "\\tau",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 63,
    formula: "\\upsilon",
    latex: "\\upsilon",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 64,
    formula: "\\psi",
    latex: "\\psi",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 65,
    formula: "\\omega",
    latex: "\\omega",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 66,
    formula: "\\chi",
    latex: "\\chi",
    type: "greek",
    fontSize: 15,
  },
];
