export const formulas = [
  {
    id: 1,
    formula: "\\sqrt{x}",
    latex: "\\sqrt{}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 2,
    formula: "\\frac{x}{y}",
    latex: "\\frac{}{}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 3,
    formula: "\\sum_y^x",
    latex: "\\sum_{}^{}",
    type: "basic",
    fontSize: 10,
    name: "sum",
  },
  {
    id: 4,
    formula: "x^y",
    latex: "\\^{}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 5,
    formula: "x^2",
    latex: "\\^{2}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 6,
    formula: "x_y",
    latex: "\\_{}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 7,
    formula: "\\log_x y",
    latex: "\\log_{} {}",
    type: "basic",
    fontSize: 10,
  },
  {
    id: 8,
    formula: "\\prod_x^y",
    latex: "\\prod_{}^{}",
    type: "basic",
    fontSize: 10,
    name: "prod",
  },

  {
    id: 9,
    formula: "\\int",
    latex: "\\int",
    type: "basic",
    fontSize: 15,
    name: "int",
  },
  {
    id: 10,
    formula: "\\int_{x}^{y}",
    latex: "\\int",
    type: "basic",
    fontSize: 15,
    name: "int",
  },
  {
    id: 11,
    formula: "\\oint",
    latex: "\\oint",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 12,
    formula: "\\lim_{x\\to y}",
    latex: "\\lim_{{x} \\to {}}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 13,
    formula: "\\lim_{x\\to \\infty}",
    latex: "\\lim_{{x} \\to \\infty}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 35,
    formula: "\\sin",
    latex: "\\sin",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 36,
    formula: "\\cos",
    latex: "\\cos",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 37,
    formula: "\\tan",
    latex: "\\tan",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 38,
    formula: "\\cot",
    latex: "\\cot",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 39,
    formula: "\\sin^{-1}",
    latex: "\\sin^{-1}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 40,
    formula: "\\cos^{-1}",
    latex: "\\cos^{-1}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 41,
    formula: "\\log_{10} y",
    latex: "\\log_{10} {}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 42,
    formula: "\\log_2 y",
    latex: "\\log_2 {}",
    type: "basic",
    fontSize: 15,
  },

  {
    id: 43,
    formula: "\\ln_y x",
    latex: "\\ln_{} {}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 44,
    formula: "\\ln x",
    latex: "\\ln {}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 45,
    formula: "\\ln_{10} x",
    latex: "\\ln_{10} {}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 14,
    formula: "\\pi",
    latex: "\\pi",
    type: "basic",
    fontSize: 20,
  },
  {
    id: 15,
    formula: "\\infty",
    latex: "\\infty",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 16,
    formula: "\\to",
    latex: "\\to",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 17,
    formula: "\\alpha",
    latex: "\\alpha",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 18,
    formula: "\\beta",
    latex: "\\beta",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 19,
    formula: "\\gamma",
    latex: "\\gamma",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 20,
    formula: "\\delta",
    latex: "\\delta",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 21,
    formula: "\\epsilon",
    latex: "\\epsilon",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 22,
    formula: "\\zeta",
    latex: "\\zeta",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 23,
    formula: "\\eta",
    latex: "\\eta",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 24,
    formula: "\\theta",
    latex: "\\theta",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 25,
    formula: "\\iota",
    latex: "\\iota",
    type: "greek",
    fontSize: 15,
  },
  
  
  // latex vectors
  
  {
    id: 27,
    formula: "\\overleftarrow{xy}",
    latex: "\\overleftarrow{xy}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 28,
    formula: "\\overline{xy}",
    latex: "\\overline{xy}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 29,
    formula: "\\overrightarrow{xy}",
    latex: "\\overrightarrow{xy}",
    type: "basic",
    fontSize: 15,
  },
  {
    id: 30,
    formula: "\\lambda",
    latex: "\\lambda",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 31,
    formula: "\\mu",
    latex: "\\mu",
    type: "greek",
    fontSize: 15,
  },
  {
    id: 32,
    formula: "\\phi",
    latex: "\\phi",
    type: "greek",
    fontSize: 15,
  }
];
