export const formulas = [
  {
    id: 1,
    formula: "\\sqrt{x}",
    latex: "\\sqrt{}",
    type: "math",
    fontSize: 15,
  },
  {
    id: 2,
    formula: "\\frac{x}{y}",
    latex: "\\frac{}{}",
    type: "math",
    fontSize: 15,
  },
  {
    id: 3,
    formula: "\\sum_y^x",
    latex: "\\sum_{}^{}",
    type: "math",
    fontSize: 10,
    name: "sum",
  },
  {
    id: 4,
    formula: "x^y",
    latex: "\\^{}",
    type: "math",
    fontSize: 15,
  },
  {
    id: 5,
    formula: "x^2",
    latex: "\\^{2}",
    type: "math",
    fontSize: 15,
  },
  {
    id: 6,
    formula: "x_y",
    latex: "\\_{}",
    type: "math",
    fontSize: 15,
  },
  {
    id: 7,
    formula: "\\log_x y",
    latex: "\\log_{} {}",
    type: "math",
    fontSize: 10,
  },
  {
    id: 8,
    formula: "\\prod_x^y",
    latex: "\\prod_{}^{}",
    type: "math",
    fontSize: 10,
    name: "prod",
  },

  {
    id: 9,
    formula: "\\int",
    latex: "\\int",
    type: "math",
    fontSize: 15,
    name: "int",
  },
  {
    id: 15,
    formula: "\\int_{x}^{y}",
    latex: "\\int",
    type: "math",
    fontSize: 15,
    name: "int",
  },
  {
    id: 11,
    formula: "\\oint",
    latex: "\\oint",
    type: "math",
    fontSize: 15,
  },
  {
    id: 12,
    formula: "\\lim_{x\\to y}",
    latex: "\\lim_{{x} \\to {}}",
    type: "math",
    fontSize: 15,
  },
  {
    id: 13,
    formula: "\\lim_{x\\to \\infty}",
    latex: "\\lim_{{x} \\to \\infty}",
    type: "math",
    fontSize: 15,
  },
  {
    id: 35,
    formula: "\\sin",
    latex: "\\sin",
    type: "math",
    fontSize: 15,
  },
  {
    id: 36,
    formula: "\\cos",
    latex: "\\cos",
    type: "math",
    fontSize: 15,
  },
  {
    id: 37,
    formula: "\\tan",
    latex: "\\tan",
    type: "math",
    fontSize: 15,
  },
  {
    id: 38,
    formula: "\\cot",
    latex: "\\cot",
    type: "math",
    fontSize: 15,
  },
  {
    id: 39,
    formula: "\\sin^{-1}",
    latex: "\\sin^{-1}",
    type: "math",
    fontSize: 15,
  },
  {
    id: 40,
    formula: "\\cos^{-1}",
    latex: "\\cos^{-1}",
    type: "math",
    fontSize: 15,
  },
  {
    id: 41,
    formula: "\\log_10 y",
    latex: "\\log_10 {}",
    type: "math",
    fontSize: 15,
  },
  {
    id: 42,
    formula: "\\log_2 y",
    latex: "\\log_2 {}",
    type: "math",
    fontSize: 15,
  },
  
  {
    id: 43,
    formula: "\\ln_y x",
    latex: "\\ln_{} {}",
    type: "math",
    fontSize: 15,
  },
  {
    id: 44,
    formula: "\\ln x",
    latex: "\\ln {}",
    type: "math",
    fontSize: 15,
  },
  {
    id: 45,
    formula: "\\ln_{10} x",
    latex: "\\ln_{10} {}",
    type: "math",
    fontSize: 15,
  },
  {
    id: 14,
    formula: "\\pi",
    latex: "\\pi",
    type: "math",
    fontSize: 20,
  },
  {
    id: 15,
    formula: "\\infty",
    latex: "\\infty",
    type: "math",
    fontSize: 15,
  },
  {
    id: 16,
    formula: "\\to",
    latex: "\\to",
    type: "math",
    fontSize: 15,
  },
  {
    id: 17,
    formula: "\\alpha",
    latex: "\\alpha",
    type: "math",
    fontSize: 15,
  },
  {
    id: 18,
    formula: "\\beta",
    latex: "\\beta",
    type: "math",
    fontSize: 15,
  },
  {
    id: 19,
    formula: "\\gamma",
    latex: "\\gamma",
    type: "math",
    fontSize: 15,
  },
  {
    id: 20,
    formula: "\\delta",
    latex: "\\delta",
    type: "math",
    fontSize: 15,
  },
  {
    id: 21,
    formula: "\\epsilon",
    latex: "\\epsilon",
    type: "math",
    fontSize: 15,
  },
  {
    id: 22,
    formula: "\\zeta",
    latex: "\\zeta",
    type: "math",
    fontSize: 15,
  },
  {
    id: 23,
    formula: "\\eta",
    latex: "\\eta",
    type: "math",
    fontSize: 15,
  },
  {
    id: 24,
    formula: "\\theta",
    latex: "\\theta",
    type: "math",
    fontSize: 15,
  },
  {
    id: 25,
    formula: "\\iota",
    latex: "\\iota",
    type: "math",
    fontSize: 15,
  },
  {
    id: 33,
    formula: "\\cfrac{x}{y}",
    latex: "\\cfrac{}{}",
    type: "math",
    fontSize: 15,
  },
  {
    id: 34,
    formula: "\\begin{bmatrix} x & y \\\\ z & w \\end{bmatrix}",
    latex: "\\begin{bmatrix} {x} & {x} \\\\ {x} & {x} \\end{bmatrix}",
    type: "math",
    fontSize: 15,
  },
];
